apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData: {}
    version: 1

  - name: Prometheus-Production
    type: prometheus
    access: proxy
    url: http://video-conference-prometheus-prod:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 30s
      queryTimeout: 120s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger-uid
    secureJsonData: {}
    version: 1
